Department.create_with(rep: 'James').find_or_create_by(name: 'Pharmacy')
Department.create_with(rep: 'Leah').find_or_create_by(name: 'Laboratory')
Department.create_with(rep: 'Janet').find_or_create_by(name: 'Facility')
Department.create_with(rep: 'Edith').find_or_create_by(name: 'Theatre')
# Department.create_with(rep: 'Lynn').find_or_create_by(name: 'Code')